CREATE TABLE TOOL_COMPARE_URL_REG (
    ID_URL_HEADER VARCHAR(100) PRIMARY KEY NOT NULL, -- url + | + header
    ALIASES_URL  VARCHAR(100)  NOT NULL UNIQUE, -- url别名，如:T4-常规报文头
    URL VARCHAR(100) NOT NULL,
    HEADER VARCHAR(100) NOT NULL UNIQUE,
    REG_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TOOL_COMPARE_JDBC_REG (
    ID_URL_USER VARCHAR(100) PRIMARY KEY NOT NULL, -- url + | + user
    ALIASES_JDBC  VARCHAR(100)  NOT NULL UNIQUE, -- jdbc别名，如:T4-应用库
    URL VARCHAR(100) NOT NULL,
    JDBC_USER VARCHAR(100) NOT NULL,
    JDBC_PASSWORD VARCHAR(100) NOT null,
    JDBC_TYPE VARCHAR(100) NOT null,
    REG_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);
